# Generated by Django 5.2.7 on 2025-10-17 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=18, max_length=2)),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('X', 'Prefiero no decir')], default='X')),
                ('audifonos', models.IntegerField(max_length=2, validators=[django.core.validators.MaxValueValidator(24)])),
                ('volume', models.CharField(choices=[('A', 'Bajo'), ('M', 'Medio'), ('B', 'Alto')], default='M')),
                ('noise_cancelation', models.BooleanField(default=False)),
            ],
        ),
    ]
