# Generated by Django 5.2.7 on 2025-10-17 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medition',
            name='noise_value',
            field=models.IntegerField(default=20000, max_length=5, validators=[django.core.validators.MaxValueValidator(22000)]),
        ),
    ]
