# Generated by Django 5.2.7 on 2025-10-17 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_medition_noise_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medition',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MaxLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='medition',
            name='audifonos',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='medition',
            name='noise_value',
            field=models.IntegerField(default=20000, validators=[django.core.validators.MaxValueValidator(22000), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
