# Generated by Django 5.2.7 on 2025-10-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_medition_age_alter_medition_audifonos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medition',
            old_name='audifonos',
            new_name='horas_audifonos',
        ),
    ]
